---
debug: false
quickstack: /usr/share/openstack-foreman-installer/config/quickstack.yaml.erb
hostgroups: /usr/share/openstack-foreman-installer/config/hostgroups.yaml
foreman_provisioning: true
# for the sub-network foreman owns
secondary_int: SECONDARY_INT
